FROM node:12.10.0-alpine
ENV LANG C.UTF-8

WORKDIR /yarilog-front

ENV baseBrouserApiUrl https://yarilog-demo.haruhiko.work/back/
ENV frontUrl https://yarilog-demo.haruhiko.work
ENV gaId UA-149009739-1

RUN apk add git && \
  git clone https://github.com/haruhikonyan/yarilog-front.git . && \
  yarn && \
  yarn run build
EXPOSE 3000
CMD /bin/sh -c 'yarn run start'
