FROM node:10.15.1-alpine
ENV LANG C.UTF-8

WORKDIR /yarilog-back

RUN apk add git && \
  apk --no-cache add --virtual builds-deps build-base python && \
  git clone https://github.com/haruhikonyan/yarilog-back.git . && \
  yarn && \
  yarn run build:prod
EXPOSE 3000
CMD /bin/sh -c 'yarn run start:prod'
